### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by aoi276** [aoi276/furima-34261#10]
# フリマアプリのURL
https://furima-34261.herokuapp.com/

# Basic認証のIDとパスワード
ID:admin
パスワード:2222

# 出品者用のメールアドレスとパスワード
メースアドレス：yama-yama2411@i.softbank.jp
パスワード：aoi000

# 購入者用のメールアドレスとパスワード
メースアドレス：shankoucangsheng@gmail.com
パスワード：furima000

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **本番環境で投稿した商品画像が、S3に保存されるようにしましょう**

- [x] **ログイン状態の出品者以外のユーザーのみ、必要な情報を適切に入力すると、商品の購入ができるようにしましょう**

- [x] **クレジットカード決済ができるようにしましょう**
正しいカード情報を入力しても、以下のエラーメッセージが出て購入ができません。

<img width="1150" alt="スクリーンショット 2021-06-09 10 58 09" src="https://user-images.githubusercontent.com/62644781/121280649-9bc5f180-c911-11eb-9ae0-f44a6578b788.png">
入力したカード情報

```
カード番号　     4242424242424242 
有効期限　          3月　23年
セキュリティコード　  123
```
※上記により、購入後の動作確認ができておりません。次回ご提出時に確認させていただきます。
修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/121449774-6d114f00-c9d5-11eb-9758-a64f2622717c.png)
